import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Visualizar() {

    const [message, setMessage] = useState("");

    const [data, setData] = useState<any>([]);

    const router = useRouter()
    const [id] = useState(router.query.id)

    const getUsers = async () => {
        if (id === undefined) {
            setMessage("Erro: Usuário não encontrado")
            return
        };

        await axios.get('http://localhost:8080/tarefas/' + id)
            .then((response) => {

                console.log(response.data);

                setData(response.data)
                setMessage("Detalhes do usuário!")
            }).catch((err) => {
                setMessage("Houve um erro ao visualizar usuário!")
            })
    }

    useEffect(() => {
        getUsers();
    }, [id]);

    return (
        <>
            <Head>
                <title>Cadastro Usuário</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Link href={"/"}><button type="button">Listar</button></Link>

                <h2>Detalhes do Usuário</h2>

                {message ? <p>{message}</p> : ""}

                <span>ID: {data.id}</span><br />
                <span>Codigo: {data.codigo}</span><br />
                <span>Nome: {data.nome}</span><br />
                <span>Data de nascimento: {data.nascimento}</span><br />
                <span>Foto: {data.foto}</span><br />

            </main>
        </>
    );
}
