import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import { servDelete } from '@/services/servDelete';

import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [message, setMessage] = useState("")

  const [data, setData] = useState<any[]>([]);

  const getUsers = async () => {
    await axios.get('http://localhost:8080/tarefas')
      .then((response) => {
        setData(response.data);

        setMessage("Usuários listados com sucesso!")

      }).catch((err) => {
        setMessage("Erro ao listar usuários!")
        throw err;
      })
  }

  useEffect(() => {
    getUsers()
  }, []);

  const deleteUser = async (idUser: string) => {
    if (window.confirm('Tem certeza que deseja apagar?')) {
      const response = await servDelete('http://localhost:8080/tarefas/' + idUser);
      setMessage("Usuário Deletado");
      getUsers();
    }
  }

  return (
    <>
      <Head>
        <title>Cadastro Usuário</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Link href={"/cadastrar"}><button type="button">Cadastrar</button></Link>

        <h2>Listar Usuário</h2>

        {message ? <p>{message}</p> : ""}

        {data.map(user => (
          <div key={user.id}>
            <span>Foto: {user.foto}</span><br />
            <span>Id: {user.id}</span><br />
            <span>Código: {user.codigo}</span><br />
            <span>Nome: {user.nome}</span><br />
            <span typeof="Date">Data de Nascimento: {user.nascimento}</span><br />
            <Link href={`/visualizar/${user.id}`}><button type="button">Visualizar</button></Link>{"  "}
            <Link href={`/editar/${user.id}`}><button type="button">Editar</button></Link>{"  "}
            <button type='button' onClick={() => deleteUser(user.id)}>Apagar</button>{" "}<br />
            <hr />
          </div>
        ))}

        <br /><br /><br /><br /><br />

      </main>
    </>
  );
}
