import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export default function Editar() {

    const [data, setData] = useState({
        id: '',
        codigo: '',
        nome: '',
        nascimento: '',
        foto: '',
    });

    const [message, setMessage] = useState("");

    const router = useRouter();
    const [id] = useState(router.query.id);
    const getUser = async () => {

        if (id === undefined) {
            setMessage("Erro: Usuário não encontrado!");
            return
        }
        await axios.get("http://localhost:8080/tarefas/" + id)
            .then((response) => {
                setData(response.data.user);
            }).catch((err) => {

                setMessage("Erro: Tente mais tarde!");
            });
    }

    useEffect(() => {
        getUser();
    }, [id]);

    const valueInput = (e: any) => setData({ ...data, [e.target.name]: e.target.value });

    const editUser = async (e: any) => {

        e.preventDefault();

        const headers = {
            'headers': {
                'Content-Type': 'application/json'
            }
        }

        await axios.put('http://localhost:8080/tarefas/' + id, data, headers)
            .then((response) => {
                setMessage(response.data.mensagem);
            }).catch((err) => {
                setMessage("Ocooreu um erro ao editar")
            });

    }

    return (
        <>
            <Head>
                <title>CRUD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <Link href={"/"}><button type='button'>Listar</button></Link>{" "}
                <Link href={`/visualizar/${data.id}`}><button type='button'>Visualizar</button></Link>{" "}

                <h2>Editar Usuário</h2>

                {message ? <p>{message}</p> : ""}

                <form onSubmit={editUser}>
                    <input type="hidden" name="id" value={data.id} />

                    <label>Código: </label>
                    <input type="text" name="codigo" placeholder="Digite o código:" onChange={valueInput} value={data.codigo} /><br /><br />

                    <label>Nome: </label>
                    <input type="text" name="nome" placeholder="Digite o seu Nome:" onChange={valueInput} value={data.nome} /><br /><br />

                    <label>Data de nascimento: </label>
                    <input type="date" name="nascimento" onChange={valueInput} value={data.nascimento} /><br /><br />

                    <label htmlFor="foto">Foto:</label>
                    <input type="file" id="foto" name="foto" onChange={valueInput} value={data.foto} /><br /><br />


                    <button type="submit">Salvar</button>

                </form>

            </main>
        </>
    )
}
